In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

In [ ]:
# 1. 데이터 준비
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()
x_train = x_train.astype("float32") / 255.0
x_test  = x_test.astype("float32") / 255.0

x_train = x_train[..., tf.newaxis]  # (60000, 28, 28, 1)
x_test  = x_test[..., tf.newaxis]   # (10000, 28, 28, 1)

# one-hot 인코딩
Y_train = keras.utils.to_categorical(y_train, 10)
Y_test  = keras.utils.to_categorical(y_test, 10)

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
# 2. 모델 구성 (간단 CNN, 빠른 학습용)
model = keras.Sequential([
    layers.Input(shape=(28,28,1)),

    layers.Conv2D(32, (3,3), activation='relu', padding='same'),
    layers.MaxPooling2D((2,2)),

    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

In [ ]:
# 3. 모델 컴파일
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

In [ ]:
# 4. 학습 (빠르게)
history = model.fit(
    x_train, Y_train,
    validation_split=0.2,
    epochs=5,      # 에포크 줄여서 학습 시간 단축
    batch_size=128,
    verbose=1
)

Epoch 1/5
375/375 ━━━━━━━━━━━━━━━━━━━━ 28s 70ms/step - accuracy: 0.8520 - loss: 0.5490 - val_accuracy: 0.9711 - val_loss: 0.1032
Epoch 2/5
375/375 ━━━━━━━━━━━━━━━━━━━━ 44s 79ms/step - accuracy: 0.9731 - loss: 0.0918 - val_accuracy: 0.9806 - val_loss: 0.0679
Epoch 3/5
375/375 ━━━━━━━━━━━━━━━━━━━━ 26s 68ms/step - accuracy: 0.9819 - loss: 0.0598 - val_accuracy: 0.9812 - val_loss: 0.0626
Epoch 4/5
375/375 ━━━━━━━━━━━━━━━━━━━━ 26s 68ms/step - accuracy: 0.9877 - loss: 0.0419 - val_accuracy: 0.9793 - val_loss: 0.0661
Epoch 5/5
375/375 ━━━━━━━━━━━━━━━━━━━━ 40s 66ms/step - accuracy: 0.9902 - loss: 0.0336 - val_accuracy: 0.9812 - val_loss: 0.0632


In [ ]:
# 5. 예측 및 평가
y_pred = model.predict(x_test)
y_test_class = np.argmax(Y_test, axis=1)
y_pred_class = np.argmax(y_pred, axis=1)

print(classification_report(y_test_class, y_pred_class))
print(confusion_matrix(y_test_class, y_pred_class))

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.99      1.00      0.99      1135
           2       0.98      0.97      0.98      1032
           3       0.97      0.99      0.98      1010
           4       0.99      0.98      0.99       982
           5       1.00      0.97      0.98       892
           6       0.98      0.98      0.98       958
           7       0.98      0.98      0.98      1028
           8       0.97      0.98      0.98       974
           9       0.98      0.98      0.98      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000

[[ 970    0    2    0    0    1    3    1    3    0]
 [   0 1130    1    2    0    0    2    0    0    0]
 [   2    3 1005    5    1    0    1    8    7    0]
 [   0    0    2 1004    0    0    0    0